# Generated by Django 6.0.1 on 2026-01-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KelasTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rute', models.CharField(max_length=200)),
                ('jam_berangkat', models.TimeField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemesanan.kelastravel')),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penumpang', models.CharField(max_length=200)),
                ('nomor_kursi', models.CharField(max_length=10)),
                ('harga_tiket', models.IntegerField()),
                ('tanggal_pesan', models.DateTimeField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemesanan.jadwal')),
            ],
        ),
    ]
