# Generated by Django 5.2 on 2026-01-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0003_alter_jadwal_id_alter_kelastravel_id_alter_tiket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='mobil',
            field=models.CharField(default='Toyota Hiace', max_length=100),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='sopir',
            field=models.CharField(default='Bpk. Supardi', max_length=100),
        ),
    ]
