# Generated by Django 5.2 on 2026-02-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0004_jadwal_mobil_jadwal_sopir'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiayaOperasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('BBM', 'Bahan Bakar'), ('SERVIS', 'Perbaikan/Servis'), ('GAJI', 'Gaji Sopir'), ('LAIN', 'Lain-lain')], max_length=20)),
                ('deskripsi', models.TextField()),
                ('nominal', models.IntegerField()),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
